const row0 = [
	{
		'id': 'Backquote',
		'class': 'letter',
		'rus': 'ё',
		'rusUp': 'Ё',
		'capRus': 'Ё',
		'capRusS': 'ё',
		'capEn': '`',
		'capEnS': '~',
		'eng': '`',
		'engUp': '~',
	},
	{
		'id': 'Digit1',
		'class': 'letter',
		'rus': '1',
		'rusUp': '!',
		'capRus': '1',
		'capRusS': '!',
		'capEn': '1',
		'capEnS': '!',
		'eng': '1',
		'engUp': '!',
	},
	{
		'id': 'Digit2',
		'class': 'letter',
		'rus': '2',
		'rusUp': '"',
		'capRus': '2',
		'capRusS': '"',
		'capEn': '2',
		'capEnS': '@',
		'eng': '2',
		'engUp': '@',
	},
	{
		'id': 'Digit3',
		'class': 'letter',
		'rus': '3',
		'rusUp': '№',
		'capRus': '3',
		'capRusS': '№',
		'capEn': '3',
		'capEnS': '#',
		'eng': '3',
		'engUp': '#',
	},
	{
		'id': 'Digit4',
		'class': 'letter',
		'rus': '4',
		'rusUp': ';',
		'capRus': '4',
		'capRusS': ';',
		'capEn': '4',
		'capEnS': '$',
		'eng': '4',
		'engUp': '$',
	},
	{
		'id': 'Digit5',
		'class': 'letter',
		'rus': '5',
		'rusUp': '%',
		'capRus': '5',
		'capRusS': '%',
		'capEn': '5',
		'capEnS': '%',
		'eng': '5',
		'engUp': '%',
	},
	{
		'id': 'Digit6',
		'class': 'letter',
		'rus': '6',
		'rusUp': ':',
		'capRus': '6',
		'capRusS': ':',
		'capEn': '6',
		'capEnS': '^',
		'eng': '6',
		'engUp': '^',
	},
	{
		'id': 'Digit7',
		'class': 'letter',
		'rus': '7',
		'rusUp': '?',
		'capRus': '7',
		'capRusS': '?',
		'capEn': '7',
		'capEnS': '&',
		'eng': '7',
		'engUp': '&',
	},
	{
		'id': 'Digit8',
		'class': 'letter',
		'rus': '8',
		'rusUp': '*',
		'capRus': '8',
		'capRusS': '*',
		'capEn': '8',
		'capEnS': '*',
		'eng': '8',
		'engUp': '*',
	},
	{
		'id': 'Digit9',
		'class': 'letter',
		'rus': '9',
		'rusUp': '(',
		'capRus': '9',
		'capRusS': '(',
		'capEn': '9',
		'capEnS': '(',
		'eng': '9',
		'engUp': '(',
	},
	{
		'id': 'Digit0',
		'class': 'letter',
		'rus': '0',
		'rusUp': ')',
		'capRus': '0',
		'capRusS': ')',
		'capEn': '0',
		'capEnS': ')',
		'eng': '0',
		'engUp': ')',
	},
	{
		'id': 'Minus',
		'class': 'letter',
		'rus': '-',
		'rusUp': '_',
		'capRus': '-',
		'capRusS': '_',
		'capEn': '-',
		'capEnS': '_',
		'eng': '-',
		'engUp': '_',
	},
	{
		'id': 'Equal',
		'class': 'letter',
		'rus': '=',
		'rusUp': '+',
		'capRus': '=',
		'capRusS': '+',
		'capEn': '=',
		'capEnS': '+',
		'eng': '=',
		'engUp': '+',
	},
	{
		'id': 'Backspace',
		'class': 'grow1',
		'rus': 'Backspace',
		'rusUp': 'Backspace',
		'capRus': 'Backspace',
		'capRusS': 'Backspace',
		'capEn': 'Backspace',
		'capEnS': 'Backspace',
		'eng': 'Backspace',
		'engUp': 'Backspace',
	},
];
const row1 = [
	{
		'id': 'Tab',
		'class': 'grow1',
		'rus': 'Tab',
		'rusUp': 'Tab',
		'capRus': 'Tab',
		'capRusS': 'Tab',
		'capEn': 'Tab',
		'capEnS': 'Tab',
		'eng': 'Tab',
		'engUp': 'Tab',
	},
	{
		'id': 'KeyQ',
		'class': 'letter',
		'rus': 'й',
		'rusUp': 'Й',
		'capRus': 'Й',
		'capRusS': 'й',
		'capEn': 'Q',
		'capEnS': 'q',
		'eng': 'q',
		'engUp': 'Q',
	},
	{
		'id': 'KeyW',
		'class': 'letter',
		'rus': 'ц',
		'rusUp': 'Ц',
		'capRus': 'Ц',
		'capRusS': 'ц',
		'capEn': 'W',
		'capEnS': 'w',
		'eng': 'w',
		'engUp': 'W',
	},
	{
		'id': 'KeyE',
		'class': 'letter',
		'rus': 'у',
		'rusUp': 'У',
		'capRus': 'У',
		'capRusS': 'у',
		'capEn': 'E',
		'capEnS': 'e',
		'eng': 'e',
		'engUp': 'E',
	},
	{
		'id': 'KeyR',
		'class': 'letter',
		'rus': 'к',
		'rusUp': 'К',
		'capRus': 'К',
		'capRusS': 'к',
		'capEn': 'R',
		'capEnS': 'r',
		'eng': 'r',
		'engUp': 'R',
	},
	{
		'id': 'KeyT',
		'class': 'letter',
		'rus': 'е',
		'rusUp': 'Е',
		'capRus': 'Е',
		'capRusS': 'е',
		'capEn': 'T',
		'capEnS': 't',
		'eng': 't',
		'engUp': 'T',
	},
	{
		'id': 'KeyY',
		'class': 'letter',
		'rus': 'н',
		'rusUp': 'Н',
		'capRus': 'Н',
		'capRusS': 'н',
		'capEn': 'Y',
		'capEnS': 'y',
		'eng': 'y',
		'engUp': 'Y',
	},
	{
		'id': 'KeyU',
		'class': 'letter',
		'rus': 'г',
		'rusUp': 'Г',
		'capRus': 'Г',
		'capRusS': 'г',
		'capEn': 'U',
		'capEnS': 'u',
		'eng': 'u',
		'engUp': 'U',
	},
	{
		'id': 'KeyI',
		'class': 'letter',
		'rus': 'ш',
		'rusUp': 'Ш',
		'capRus': 'Ш',
		'capRusS': 'ш',
		'capEn': 'I',
		'capEnS': 'i',
		'eng': 'i',
		'engUp': 'I',
	},
	{
		'id': 'KeyO',
		'class': 'letter',
		'rus': 'щ',
		'rusUp': 'Щ',
		'capRus': 'Щ',
		'capRusS': 'щ',
		'capEn': 'O',
		'capEnS': 'o',
		'eng': 'o',
		'engUp': 'O',
	},
	{
		'id': 'KeyP',
		'class': 'letter',
		'rus': 'з',
		'rusUp': 'З',
		'capRus': 'З',
		'capRusS': 'з',
		'capEn': 'P',
		'capEnS': 'p',
		'eng': 'p',
		'engUp': 'P',
	},
	{
		'id': 'BracketLeft',
		'class': 'letter',
		'rus': 'х',
		'rusUp': 'Х',
		'capRus': 'Х',
		'capRusS': 'х',
		'capEn': '[',
		'capEnS': '{',
		'eng': '[',
		'engUp': '{',
	},
	{
		'id': 'BracketRight',
		'class': 'letter',
		'rus': 'ъ',
		'rusUp': 'Ъ',
		'capRus': 'Ъ',
		'capRusS': 'ъ',
		'capEn': ']',
		'capEnS': '}',
		'eng': ']',
		'engUp': '}',
	},
	{
		'id': 'Backslash',
		'class': 'grow1',
		'rus': '\\',
		'rusUp': '/',
		'capRus': '\\',
		'capRusS': '/',
		'capEn': '\\',
		'capEnS': '|',
		'eng': '\\',
		'engUp': '|',
	},
];
const row2 = [
	{
		'id': 'CapsLock',
		'class': 'grow1',
		'rus': 'CapsLock',
		'rusUp': 'CapsLock',
		'capRus': 'CapsLock',
		'capRusS': 'CapsLock',
		'capEn': 'CapsLock',
		'capEnS': 'CapsLock',
		'eng': 'CapsLock',
		'engUp': 'CapsLock',
	},
	{
		'id': 'KeyA',
		'class': 'letter',
		'rus': 'ф',
		'rusUp': 'Ф',
		'capRus': 'Ф',
		'capRusS': 'ф',
		'capEn': 'A',
		'capEnS': 'a',
		'eng': 'a',
		'engUp': 'A',
	},
	{
		'id': 'KeyS',
		'class': 'letter',
		'rus': 'ы',
		'rusUp': 'Ы',
		'capRus': 'Ы',
		'capRusS': 'ы',
		'capEn': 'S',
		'capEnS': 's',
		'eng': 's',
		'engUp': 'S',
	},
	{
		'id': 'KeyD',
		'class': 'letter',
		'rus': 'в',
		'rusUp': 'В',
		'capRus': 'В',
		'capRusS': 'в',
		'capEn': 'D',
		'capEnS': 'd',
		'eng': 'd',
		'engUp': 'D',
	},
	{
		'id': 'KeyF',
		'class': 'letter',
		'rus': 'а',
		'rusUp': 'А',
		'capRus': 'А',
		'capRusS': 'а',
		'capEn': 'F',
		'capEnS': 'f',
		'eng': 'f',
		'engUp': 'F',
	},
	{
		'id': 'KeyG',
		'class': 'letter',
		'rus': 'п',
		'rusUp': 'П',
		'capRus': 'П',
		'capRusS': 'п',
		'capEn': 'G',
		'capEnS': 'g',
		'eng': 'g',
		'engUp': 'G',
	},
	{
		'id': 'KeyH',
		'class': 'letter',
		'rus': 'р',
		'rusUp': 'Р',
		'capRus': 'Р',
		'capRusS': 'р',
		'capEn': 'H',
		'capEnS': 'h',
		'eng': 'h',
		'engUp': 'H',
	},
	{
		'id': 'KeyJ',
		'class': 'letter',
		'rus': 'о',
		'rusUp': 'О',
		'capRus': 'О',
		'capRusS': 'о',
		'capEn': 'J',
		'capEnS': 'j',
		'eng': 'j',
		'engUp': 'J',
	},
	{
		'id': 'KeyK',
		'class': 'letter',
		'rus': 'л',
		'rusUp': 'Л',
		'capRus': 'Л',
		'capRusS': 'л',
		'capEn': 'K',
		'capEnS': 'k',
		'eng': 'k',
		'engUp': 'K',
	},
	{
		'id': 'KeyL',
		'class': 'letter',
		'rus': 'д',
		'rusUp': 'Д',
		'capRus': 'Д',
		'capRusS': 'д',
		'capEn': 'L',
		'capEnS': 'l',
		'eng': 'l',
		'engUp': 'L',
	},
	{
		'id': 'Semicolon',
		'class': 'letter',
		'rus': 'ж',
		'rusUp': 'Ж',
		'capRus': 'Ж',
		'capRusS': 'ж',
		'capEn': ';',
		'capEnS': ':',
		'eng': ';',
		'engUp': ':',
	},
	{
		'id': 'Quote',
		'class': 'letter',
		'rus': 'э',
		'rusUp': 'Э',
		'capRus': 'Э',
		'capRusS': 'э',
		'capEn': '\'',
		'capEnS': '"',
		'eng': '\'',
		'engUp': '"',
	},
	{
		'id': 'Enter',
		'class': 'grow3',
		'rus': 'Enter',
		'rusUp': 'Enter',
		'capRus': 'Enter',
		'capRusS': 'Enter',
		'capEn': 'Enter',
		'capEnS': 'Enter',
		'eng': 'Enter',
		'engUp': 'Enter',
	},

];
const row3 = [
	{
		'id': 'ShiftLeft',
		'class': 'grow1',
		'rus': 'Shift',
		'rusUp': 'Shift',
		'capRus': 'Shift',
		'capRusS': 'Shift',
		'capEn': 'Shift',
		'capEnS': 'Shift',
		'eng': 'Shift',
		'engUp': 'Shift',
	},
	{
		'id': 'KeyZ',
		'class': 'letter',
		'rus': 'я',
		'rusUp': 'Я',
		'capRus': 'Я',
		'capRusS': 'я',
		'capEn': 'Z',
		'capEnS': 'z',
		'eng': 'z',
		'engUp': 'Z',
	},
	{
		'id': 'KeyX',
		'class': 'letter',
		'rus': 'ч',
		'rusUp': 'Ч',
		'capRus': 'Ч',
		'capRusS': 'ч',
		'capEn': 'X',
		'capEnS': 'x',
		'eng': 'x',
		'engUp': 'X',
	},
	{
		'id': 'KeyC',
		'class': 'letter',
		'rus': 'с',
		'rusUp': 'С',
		'capRus': 'С',
		'capRusS': 'с',
		'capEn': 'C',
		'capEnS': 'c',
		'eng': 'c',
		'engUp': 'C',
	},
	{
		'id': 'KeyV',
		'class': 'letter',
		'rus': 'м',
		'rusUp': 'М',
		'capRus': 'М',
		'capRusS': 'м',
		'capEn': 'V',
		'capEnS': 'v',
		'eng': 'v',
		'engUp': 'V',
	},
	{
		'id': 'KeyB',
		'class': 'letter',
		'rus': 'и',
		'rusUp': 'И',
		'capRus': 'И',
		'capRusS': 'и',
		'capEn': 'B',
		'capEnS': 'b',
		'eng': 'b',
		'engUp': 'B',
	},
	{
		'id': 'KeyN',
		'class': 'letter',
		'rus': 'т',
		'rusUp': 'Т',
		'capRus': 'Т',
		'capRusS': 'т',
		'capEn': 'N',
		'capEnS': 'n',
		'eng': 'n',
		'engUp': 'N',
	},
	{
		'id': 'KeyM',
		'class': 'letter',
		'rus': 'ь',
		'rusUp': 'Ь',
		'capRus': 'Ь',
		'capRusS': 'ь',
		'capEn': 'M',
		'capEnS': 'm',
		'eng': 'm',
		'engUp': 'M',
	},
	{
		'id': 'Comma',
		'class': 'letter',
		'rus': 'б',
		'rusUp': 'Б',
		'capRus': 'Б',
		'capRusS': 'б',
		'capEn': ',',
		'capEnS': '<',
		'eng': ',',
		'engUp': '<',
	},
	{
		'id': 'Period',
		'class': 'letter',
		'rus': 'ю',
		'rusUp': 'Ю',
		'capRus': 'Ю',
		'capRusS': 'ю',
		'capEn': '.',
		'capEnS': '>',
		'eng': '.',
		'engUp': '>',
	},
	{
		'id': 'Slash',
		'class': 'letter',
		'rus': '.',
		'rusUp': ',',
		'capRus': '.',
		'capRusS': ',',
		'capEn': '/',
		'capEnS': '?',
		'eng': '/',
		'engUp': '?',
	},

	{
		'id': 'ShiftRight',
		'class': 'grow1',
		'rus': 'Shift',
		'rusUp': 'Shift',
		'capRus': 'Shift',
		'capRusS': 'Shift',
		'capEn': 'Shift',
		'capEnS': 'Shift',
		'eng': 'Shift',
		'engUp': 'Shift',
	},
];
const row4 = [
	{
		'id': 'ControlLeft',
		'class': 'letter',
		'rus': 'Ctrl',
		'rusUp': 'Ctrl',
		'capRus': 'Ctrl',
		'capRusS': 'Ctrl',
		'capEn': 'Ctrl',
		'capEnS': 'Ctrl',
		'eng': 'Ctrl',
		'engUp': 'Ctrl',
	},
	{
		'id': 'MetaLeft',
		'class': 'letter',
		'rus': 'Win',
		'rusUp': 'Win',
		'capRus': 'Win',
		'capRusS': 'Win',
		'capEn': 'Win',
		'capEnS': 'Win',
		'eng': 'Win',
		'engUp': 'Win',
	},
	{
		'id': 'AltLeft',
		'class': 'letter',
		'rus': 'Alt',
		'rusUp': 'Alt',
		'capRus': 'Alt',
		'capRusS': 'Alt',
		'capEn': 'Alt',
		'capEnS': 'Alt',
		'eng': 'Alt',
		'engUp': 'Alt',
	},
	{
		'id': 'Space',
		'class': 'grow3',
		'rus': 'Space',
		'rusUp': 'Space',
		'capRus': 'Space',
		'capRusS': 'Space',
		'capEn': 'Space',
		'capEnS': 'Space',
		'eng': 'Space',
		'engUp': 'Space',
	},
	{
		'id': 'AltRight',
		'class': 'letter',
		'rus': 'Alt',
		'rusUp': 'Alt',
		'capRus': 'Alt',
		'capRusS': 'Alt',
		'capEn': 'Alt',
		'capEnS': 'Alt',
		'eng': 'Alt',
		'engUp': 'Alt',
	},
	{
		'id': 'ControlRight',
		'class': 'letter',
		'rus': 'Ctrl',
		'rusUp': 'Ctrl',
		'capRus': 'Ctrl',
		'capRusS': 'Ctrl',
		'capEn': 'Ctrl',
		'capEnS': 'Ctrl',
		'eng': 'Ctrl',
		'engUp': 'Ctrl',
	},
	{
		'id': 'ArrowLeft',
		'class': 'letter',
		'rus': '&larr;',
		'rusUp': '&larr;',
		'capRus': '&larr;',
		'capRusS': '&larr;',
		'capEn': '&larr;',
		'capEnS': '&larr;',
		'eng': '&larr;',
		'engUp': '&larr;',
	},
	{
		'id': 'ArrowUp',
		'class': 'key-half',
		'rus': '&uarr;',
		'rusUp': '&uarr;',
		'capRus': '&uarr;',
		'capRusS': '&uarr;',
		'capEn': '&uarr;',
		'capEnS': '&uarr;',
		'eng': '&uarr;',
		'engUp': '&uarr;',
	},
	{
		'id': 'ArrowDown',
		'class': 'key-half',
		'rus': '&darr;',
		'rusUp': '&darr;',
		'capRus': '&darr;',
		'capRusS': '&darr;',
		'capEn': '&darr;',
		'capEnS': '&darr;',
		'eng': '&darr;',
		'engUp': '&darr;',
	},
	{
		'id': 'ArrowRight',
		'class': 'letter',
		'rus': '&rarr;',
		'rusUp': '&rarr;',
		'capRus': '&rarr;',
		'capRusS': '&rarr;',
		'capEn': '&rarr;',
		'capEnS': '&rarr;',
		'eng': '&rarr;',
		'engUp': '&rarr;',
	},
];
export { row0, row1, row2, row3, row4 };