class Row {
  static row0(row0, row) {
    row0.forEach((i) => {
      const key = document.createElement('div');
      key.setAttribute('id', i.id);
      key.classList.add('key');
      key.classList.add(i.class);
      const langRu = document.createElement('span');
      const langEn = document.createElement('span');
      const capEn = document.createElement('span');
      const capEnUp = document.createElement('span');
      const capRu = document.createElement('span');
      const capRuUp = document.createElement('span');
      const capsEn = document.createElement('span');
      const capsEnUp = document.createElement('span');
      const capsRu = document.createElement('span');
      const capsRuUp = document.createElement('span');
      langRu.classList.add('hidden');
      langRu.classList.add('langRu');
      langEn.classList.add('langEn');
      capEn.classList.add('en');
      capEnUp.classList.add('hidden');
      capEnUp.classList.add('enUp');
      capRu.classList.add('ru');
      capRuUp.classList.add('hidden');
      capRuUp.classList.add('ruUp');
      capsEn.classList.add('hidden');
      capsEn.classList.add('enCap');
      capsEnUp.classList.add('hidden');
      capsEnUp.classList.add('enCapS');
      capsRu.classList.add('hidden');
      capsRu.classList.add('ruCap');
      capsRuUp.classList.add('hidden');
      capsRuUp.classList.add('ruCapS');
      capEn.innerHTML = i.eng;
      capEnUp.innerHTML = i.engUp;
      capRu.innerHTML = i.rus;
      capRuUp.innerHTML = i.rusUp;
      capsEn.innerHTML = i.capEn;
      capsEnUp.innerHTML = i.capEnS;
      capsRu.innerHTML = i.capRus;
      capsRuUp.innerHTML = i.capRusS;
      langRu.append(capRu);
      langRu.append(capRuUp);
      langRu.append(capsRu);
      langRu.append(capsRuUp);
      langEn.append(capsEn);
      langEn.append(capsEnUp);
      langEn.append(capEn);
      langEn.append(capEnUp);
      key.append(langEn);
      key.append(langRu);
      row.append(key);
    });
  }

  static row1(row1, row) {
    row1.forEach((i) => {
      const key = document.createElement('div');
      key.setAttribute('id', i.id);
      key.classList.add('key');
      key.classList.add(i.class);
      const langRu = document.createElement('span');
      const langEn = document.createElement('span');
      const capEn = document.createElement('span');
      const capEnUp = document.createElement('span');
      const capRu = document.createElement('span');
      const capRuUp = document.createElement('span');
      const capsEn = document.createElement('span');
      const capsEnUp = document.createElement('span');
      const capsRu = document.createElement('span');
      const capsRuUp = document.createElement('span');
      langRu.classList.add('hidden');
      langRu.classList.add('langRu');
      langEn.classList.add('langEn');
      capEn.classList.add('en');
      capEnUp.classList.add('hidden');
      capEnUp.classList.add('enUp');
      capRu.classList.add('ru');
      capRuUp.classList.add('hidden');
      capRuUp.classList.add('ruUp');
      capsEn.classList.add('hidden');
      capsEn.classList.add('enCap');
      capsEnUp.classList.add('hidden');
      capsEnUp.classList.add('enCapS');
      capsRu.classList.add('hidden');
      capsRu.classList.add('ruCap');
      capsRuUp.classList.add('hidden');
      capsRuUp.classList.add('ruCapS');
      capEn.innerHTML = i.eng;
      capEnUp.innerHTML = i.engUp;
      capRu.innerHTML = i.rus;
      capRuUp.innerHTML = i.rusUp;
      capsEn.innerHTML = i.capEn;
      capsEnUp.innerHTML = i.capEnS;
      capsRu.innerHTML = i.capRus;
      capsRuUp.innerHTML = i.capRusS;
      langRu.append(capRu);
      langRu.append(capRuUp);
      langRu.append(capsRu);
      langRu.append(capsRuUp);
      langEn.append(capsEn);
      langEn.append(capsEnUp);
      langEn.append(capEn);
      langEn.append(capEnUp);
      key.append(langEn);
      key.append(langRu);
      row.append(key);
    });
  }

  static row2(row2, row) {
    row2.forEach((i) => {
      const key = document.createElement('div');
      key.setAttribute('id', i.id);
      key.classList.add('key');
      key.classList.add(i.class);
      const langRu = document.createElement('span');
      const langEn = document.createElement('span');
      langRu.classList.add('langRu');
      langEn.classList.add('langEn');
      const capEn = document.createElement('span');
      const capEnUp = document.createElement('span');
      const capRu = document.createElement('span');
      const capRuUp = document.createElement('span');
      const capsEn = document.createElement('span');
      const capsEnUp = document.createElement('span');
      const capsRu = document.createElement('span');
      const capsRuUp = document.createElement('span');
      langRu.classList.add('hidden');
      capEn.classList.add('en');
      capEnUp.classList.add('hidden');
      capEnUp.classList.add('enUp');
      capRu.classList.add('ru');
      capRuUp.classList.add('hidden');
      capRuUp.classList.add('ruUp');
      capsEn.classList.add('hidden');
      capsEn.classList.add('enCap');
      capsEnUp.classList.add('hidden');
      capsEnUp.classList.add('enCapS');
      capsRu.classList.add('hidden');
      capsRu.classList.add('ruCap');
      capsRuUp.classList.add('hidden');
      capsRuUp.classList.add('ruCapS');
      capEn.innerHTML = i.eng;
      capEnUp.innerHTML = i.engUp;
      capRu.innerHTML = i.rus;
      capRuUp.innerHTML = i.rusUp;
      capsEn.innerHTML = i.capEn;
      capsEnUp.innerHTML = i.capEnS;
      capsRu.innerHTML = i.capRus;
      capsRuUp.innerHTML = i.capRusS;
      langRu.append(capRu);
      langRu.append(capRuUp);
      langRu.append(capsRu);
      langRu.append(capsRuUp);
      langEn.append(capsEn);
      langEn.append(capsEnUp);
      langEn.append(capEn);
      langEn.append(capEnUp);
      key.append(langEn);
      key.append(langRu);
      row.append(key);
    });
  }

  static row3(row3, row) {
    row3.forEach((i) => {
      const key = document.createElement('div');
      key.setAttribute('id', i.id);
      key.classList.add('key');
      key.classList.add(i.class);
      const langRu = document.createElement('span');
      const langEn = document.createElement('span');
      const capEn = document.createElement('span');
      const capEnUp = document.createElement('span');
      const capRu = document.createElement('span');
      const capRuUp = document.createElement('span');
      const capsEn = document.createElement('span');
      const capsEnUp = document.createElement('span');
      const capsRu = document.createElement('span');
      const capsRuUp = document.createElement('span');
      langRu.classList.add('hidden');
      langRu.classList.add('langRu');
      langEn.classList.add('langEn');
      capEn.classList.add('en');
      capEnUp.classList.add('hidden');
      capEnUp.classList.add('enUp');
      capRu.classList.add('ru');
      capRuUp.classList.add('hidden');
      capRuUp.classList.add('ruUp');
      capsEn.classList.add('hidden');
      capsEn.classList.add('enCap');
      capsEnUp.classList.add('hidden');
      capsEnUp.classList.add('enCapS');
      capsRu.classList.add('hidden');
      capsRu.classList.add('ruCap');
      capsRuUp.classList.add('hidden');
      capsRuUp.classList.add('ruCapS');
      capEn.innerHTML = i.eng;
      capEnUp.innerHTML = i.engUp;
      capRu.innerHTML = i.rus;
      capRuUp.innerHTML = i.rusUp;
      capsEn.innerHTML = i.capEn;
      capsEnUp.innerHTML = i.capEnS;
      capsRu.innerHTML = i.capRus;
      capsRuUp.innerHTML = i.capRusS;
      langRu.append(capRu);
      langRu.append(capRuUp);
      langRu.append(capsRu);
      langRu.append(capsRuUp);
      langEn.append(capsEn);
      langEn.append(capsEnUp);
      langEn.append(capEn);
      langEn.append(capEnUp);
      key.append(langEn);
      key.append(langRu);
      row.append(key);
    });
  }

  static row4(row4, row) {
    const keyWrap = document.createElement('div');
    keyWrap.classList.add('key-wrap');
    row4.forEach((i) => {
      const key = document.createElement('div');
      key.setAttribute('id', i.id);
      key.classList.add('key');
      key.classList.add(i.class);
      const langRu = document.createElement('span');
      const langEn = document.createElement('span');
      const capEn = document.createElement('span');
      const capEnUp = document.createElement('span');
      const capRu = document.createElement('span');
      const capRuUp = document.createElement('span');
      const capsEn = document.createElement('span');
      const capsEnUp = document.createElement('span');
      const capsRu = document.createElement('span');
      const capsRuUp = document.createElement('span');
      langRu.classList.add('hidden');
      langRu.classList.add('langRu');
      langEn.classList.add('langEn');
      capEn.classList.add('en');
      capEnUp.classList.add('hidden');
      capEnUp.classList.add('enUp');
      capRu.classList.add('ru');
      capRuUp.classList.add('hidden');
      capRuUp.classList.add('ruUp');
      capsEn.classList.add('hidden');
      capsEn.classList.add('enCap');
      capsEnUp.classList.add('hidden');
      capsEnUp.classList.add('enCapS');
      capsRu.classList.add('hidden');
      capsRu.classList.add('ruCap');
      capsRuUp.classList.add('hidden');
      capsRuUp.classList.add('ruCapS');
      capEn.innerHTML = i.eng;
      capEnUp.innerHTML = i.engUp;
      capRu.innerHTML = i.rus;
      capRuUp.innerHTML = i.rusUp;
      capsEn.innerHTML = i.capEn;
      capsEnUp.innerHTML = i.capEnS;
      capsRu.innerHTML = i.capRus;
      capsRuUp.innerHTML = i.capRusS;
      langRu.append(capRu);
      langRu.append(capRuUp);
      langRu.append(capsRu);
      langRu.append(capsRuUp);
      langEn.append(capsEn);
      langEn.append(capsEnUp);
      langEn.append(capEn);
      langEn.append(capEnUp);
      key.append(langEn);
      key.append(langRu);
      if (key.id === 'ArrowUp' || key.id === 'ArrowDown') {
        keyWrap.append(key);
        row.append(keyWrap);
      } else {
        row.append(key);
      }
    });
  }
}
// const rows = new Row();
export default Row;
